[package]
name = "engine"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2"
serde = { version = "1", features = ["derive"] }
serde-wasm-bindgen = "0.5"
rand = { version = "0.8", default-features = false }
rand_pcg = "0.3"
blake3 = { version = "1", default-features = false }
console_error_panic_hook = { version = "0.1", optional = true }

[dev-dependencies]
rand = { version = "0.8", features = ["std"] }

[features]
default = ["console_error_panic_hook"]
console_error_panic_hook = ["dep:console_error_panic_hook"]
